Edited CD v2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,8 +27,7 @@ jobs:
             echo "Pull from main branch"
             git fetch origin
             echo "Pull from main"
-            git pull origin main || {echo "git pull failed";exit 1;}
-
+            git pull origin main || { echo "git pull failed"; exit 1; }
             echo "Install requirements"
             source venv/bin/activate
             pip install -r requirements.txt
